# Copyright (C) 2022 Arthur-Irina-Mathieu
# SPDX-License-Identifier: MIT
version: '3.9'
services:
  wym_db:
    container_name: wym_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_USER: wym_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - wym_db:/var/lib/postgresql/data
    networks:
      - wym
  wym_model:
    container_name: wym_model
    image: quay.io/codait/max-text-summarizer
    restart: always
    ports:
      - "3000:5000"
    expose:
      - "3000"
    networks:
      - wym
  wym_web:
    container_name: wym_web
    build: ../app
    links:
      - wym_db
      - wym_model
    ports:
      - "8000:5000"
    restart: always
    depends_on:
      - wym_model
      - wym_db
    networks:
      - wym
volumes:
  wym_db:
networks:
  wym: